# Stage 1 : Build the go application
FROM golang:1.21 AS builder

#  set the working directory inside the container

WORKDIR /app

#Copy Go module and install dependencies
COPY go.mod go.sum ./
RUN go mod download

# copy the rest of the application files
COPY . .

# BUILD the application
RUN  go build -o main .
# stage 2 : Create light weight container
FROM alpine:latest

# set working directory
WORKDIR  /root/

# copy the compiled binary from the builder stage
COPY --from=builder /app/main .

# expose port
EXPOSE 8080

# command to run the application
CMD ["./main"]